# Generated by Django 2.0.3 on 2018-04-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('UIN', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('F_name', models.CharField(max_length=50)),
                ('M_name', models.CharField(max_length=50)),
                ('Contact', models.CharField(max_length=10)),
                ('EmailId', models.CharField(max_length=50)),
                ('DateofBirth', models.DateField()),
                ('Certificates', models.ImageField(upload_to='')),
                ('Link', models.URLField()),
            ],
        ),
    ]
