# Generated by Django 2.0.4 on 2018-04-18 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Link',
            field=models.CharField(max_length=10000),
        ),
    ]
