# Generated by Django 2.0.4 on 2018-04-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20180418_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sec_ans',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
