# Generated by Django 2.0.4 on 2018-04-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_student_sec_ans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Certificates',
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='password', max_length=50),
        ),
    ]
