# Generated by Django 2.0.4 on 2018-04-20 01:26

import about.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_auto_20180419_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='images',
            field=models.ImageField(default='a', upload_to=about.models.get_image_path),
        ),
    ]
